name: simple deploy workflow

on: deployment

jobs:
  deploy:
    name: Deploy workflow
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: ls
      run: ls -la

    - name: deploy
      run: |
          # deployment logic goes here
          sleep 10
          # instead we randomly succeed or fail the deployment
          exit $(( $RANDOM % 10 >= 5 ))
