name: test on failure of specific step

on:
  push:

jobs:
  test-failure-behaviour:
    name: Test the failure behaviour
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: 1st step
      run: exit 1

    - name: 2nd step
      id: secondStep
      run: exit 0

    - name: 3rd step
      if: ${{ failure() && steps.secondStep.outcome == 'Failure' }}
      run: echo "3rd step does run!"

    - name: 4th step
      run: echo "I should probably do not return anything"

    - name: 5th step
      if: ${{ failure() }}
      env:
          STEPS_CONTEXT: ${{ toJson(steps.secondStep) }}
      run: echo "$STEPS_CONTEXT"

    - name: 6th step
      if: ${{ failure() }}
      run: |
        echo ${{ steps.secondStep.outcome }}
        echo ${{ steps.secondStep.outcome == 'Failure' }}
        echo ${{ steps.secondStep.outcome == 'failure' }}
